title: Organisation festival GongFuCha
description: >
  Page de présentation des événements de la Luz
author: pntbr
email: stephane@brutdethe.fr
repository: pntbr/la-luz.git

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

defaults:
  - scope:
      path: ""
    values:
      layout: article

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-titles-from-headings
